### ISSUE TITLE
where does the .csv file come from for the sample code 

### ISSUE THREAD

**Issue by leoqq** [marina8888/chemkin-sensitivity-analysis#2]
so where is data/40%_0.85.csv come from? doesn't seem like it is from the sample data. Thanks a lot for the help

**Comment by marina8888** [comment]
Hi, sorry for the late reply. This data is generated by CHEMKIN in the export data option. When using this option, CHEMKIN has a habit of generating the data spread across multiple .csv sheets (depending on how many reactions your mechanism has), so I just moved all the sheets from that export into one directory.

**Comment by marina8888** [comment]
If there are no further comments, I will close this issue.
